Example1: # very basic
  cuts: "Nlep>=2;MET>=150;PTISR_LEP>=200"
  lep-cuts: ">=1OSSF"
  predefined-cuts: "Cleaning"
  user-cuts: ""

Example2: # loads of examples
  cuts: "Nlep>=3;MET>=50;MAX(SIP3D_lep)<4"
  lep-cuts: |
    >=1Mu;
    >=1Silver;
    >=1SSSF_b|DeltaR<0.5;
  predefined-cuts: "Zstar"
  user-cuts: ""
  #Example user cuts:
  #user-cuts: "lep0_pt25_jet0_pt30_dR0p4;M_jj_gt_100"

SuperBin2L: # Example SuperBin in 2L
  cuts: "Nlep==2;MET>=150;PTISR_LEP>=200;Nbjet==0;Mperp<=100;RISR_LEP>=0.6;RISR_LEP<=1;Njet_S==0;fabs(dphiMET_V)<TMath::Pi()/2.0"
  lep-cuts: |
    =2Gold;
  #  =1OSSF|mass![3.,3.2];
  #J/Psi Veto: =1OSSF|mass![3.,3.2];
  predefined-cuts: "Cleaning"
  user-cuts: ""
