histograms:
  - name: MET_RISRHigh
    type: "1D"
    expr: "MET"
    nbins: 20
    xmin: 0
    xmax: 1000
    cuts: "RISR>=0.75" # additional cut on top of base bin
    lep-cuts: "=2Gold"
    predefined-cuts: "Cleaning"

  - name: MET_RISRLow
    type: "1D"
    expr: "MET"
    nbins: 20
    xmin: 0
    xmax: 1000
    cuts: "RISR<0.75"
    lep-cuts: "=2Gold"
    predefined-cuts: "Cleaning"

  - name: PTISR_vs_RISR
    type: "2D"
    expr: "PTISR"
    yexpr: "RISR"
    nbins: 20
    xmin: 0
    xmax: 500
    nybins: 20
    ymin: 0
    ymax: 1
    cuts: "" # inherits full base bin selection
    lep-cuts: "=2Gold"
    predefined-cuts: "Cleaning"

  - name: Nlep_vs_MET
    type: "2D"
    expr: "Nlep"
    yexpr: "MET"
    nbins: 5
    xmin: 0
    xmax: 5
    nybins: 20
    ymin: 0
    ymax: 1000
    cuts: "PTISR>=200;RISR>=0.5"
    lep-cuts: "=2Gold"
    predefined-cuts: "Cleaning"

  - name: Nbjet
    type: "1D"
    expr: "Nbjet"
    nbins: 6
    xmin: 0
    xmax: 6
    cuts: "PTISR>=200"
    lep-cuts: "=2Gold"
    predefined-cuts: "Cleaning"

  - name: Mperp
    type: "1D"
    expr: "Mperp"
    nbins: 15
    xmin: 0
    xmax: 150
    cuts: "RISR>=0.6"
    lep-cuts: "=2Gold"
    predefined-cuts: "Cleaning"

