derived_variables:
  - name: M_ratio
    expr: "SafeDiv(MVa, MVb, 0.0)" # MVa / MVb; default to 0 if MVb == 0
  - name: PT3_lep
    expr: "SafeIndex(PT_lep, 2, -1.0)" # third leading lep pt; default to -1 for events with less than 3 leps

histograms:
  - name: M_ratio_vs_PT3
    type: "2D"
    expr: "M_ratio"    # X-axis
    yexpr: "PT3_lep"   # Y-axis
    nbins: 20
    xmin: 0
    xmax: 2
    nybins: 20
    ymin: 0
    ymax: 200
    cuts: ""
    lep-cuts: ""
    predefined-cuts: ""
    user-cuts: ""

  - name: M_ratio
    type: "1D"
    expr: "M_ratio"
    nbins: 20
    xmin: 0
    xmax: 2
    cuts: ""
    lep-cuts: ""
    predefined-cuts: ""
    user-cuts: ""

  - name: PTISR_vs_RISR
    type: "2D"
    expr: "PTISR"
    yexpr: "RISR"
    nbins: 20
    xmin: 250
    xmax: 800
    nybins: 64
    ymin: 0
    ymax: 1
    cuts: ""
    lep-cuts: ""
    predefined-cuts: ""
    user-cuts: ""

  - name: Mperp_RISRHigh
    type: "1D"
    expr: "Mperp"
    nbins: 64
    xmin: 0
    xmax: 150
    cuts: "RISR>=0.85"
    lep-cuts: ""
    predefined-cuts: ""
    user-cuts: ""

  - name: Mperp_RISRLow
    type: "1D"
    expr: "Mperp"
    nbins: 64
    xmin: 0
    xmax: 150
    cuts: "RISR<0.85"
    lep-cuts: ""
    predefined-cuts: ""
    user-cuts: ""
